package admin;


/**
* admin/AdminOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Patient.idl
* Sunday, February 20, 2022 12:41:36 AM EST
*/

public interface AdminOperations 
{
  boolean addAppointment (String appointmentId, appointment.AppointmentType type, int capacity);
  String removeAppointment (String appointmentId, appointment.AppointmentType type);
  String listAppointmentAvailability (appointment.AppointmentType type);
} // interface AdminOperations
