package admin;


/**
* admin/Admin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Patient.idl
* Sunday, February 20, 2022 12:41:36 AM EST
*/

public interface Admin extends AdminOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Admin
