package cobar_entity.admin;

/**
 * admin/Admin.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from
 * dams.idl Sunday, February 20, 2022 8:35:24 PM EST
 */
public interface Admin
    extends AdminOperations,
        org.omg.CORBA.Object,
        org.omg.CORBA.portable.IDLEntity {} // interface Admin
