package cobar_entity.admin;


import cobar_entity.appointment.AppointmentTypeDto;
import cobar_entity.appointment.AppointmentTypeDtoHelper;

/**
* admin/AdminPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Patient.idl
* Sunday, February 20, 2022 4:56:02 PM EST
*/

public abstract class AdminPOA extends org.omg.PortableServer.Servant
 implements AdminOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addAppointment", new java.lang.Integer (0));
    _methods.put ("removeAppointment", new java.lang.Integer (1));
    _methods.put ("listAppointmentAvailability", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // admin/Admin/addAppointment
       {
         String appointmentId = in.read_string ();
         AppointmentTypeDto type = AppointmentTypeDtoHelper.read (in);
         int capacity = in.read_long ();
         boolean $result = false;
         $result = this.addAppointment (appointmentId, type, capacity);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // admin/Admin/removeAppointment
       {
         String appointmentId = in.read_string ();
         AppointmentTypeDto type = AppointmentTypeDtoHelper.read (in);
         String $result = null;
         $result = this.removeAppointment (appointmentId, type);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // admin/Admin/listAppointmentAvailability
       {
         AppointmentTypeDto type = AppointmentTypeDtoHelper.read (in);
         String $result = null;
         $result = this.listAppointmentAvailability (type);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:admin/Admin:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Admin _this()
  {
    return AdminHelper.narrow(
    super._this_object());
  }

  public Admin _this(org.omg.CORBA.ORB orb) 
  {
    return AdminHelper.narrow(
    super._this_object(orb));
  }


} // class AdminPOA
