package cobar_entity.admin;

/**
* admin/AdminHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Patient.idl
* Sunday, February 20, 2022 4:56:02 PM EST
*/

public final class AdminHolder implements org.omg.CORBA.portable.Streamable
{
  public Admin value = null;

  public AdminHolder ()
  {
  }

  public AdminHolder (Admin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AdminHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AdminHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AdminHelper.type ();
  }

}
