package cobar_entity.admin;

import cobar_entity.appointment.AppointmentTypeDto;

/**
 * admin/AdminOperations.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from
 * Patient.idl Sunday, February 20, 2022 8:35:24 PM EST
 */
public interface AdminOperations {
  boolean addAppointment(String appointmentId, AppointmentTypeDto type, int capacity);

  String removeAppointment(String appointmentId, AppointmentTypeDto type);

  String listAppointmentAvailability(AppointmentTypeDto type);

  String listLocalAppointmentAvailability(AppointmentTypeDto type);
} // interface AdminOperations
