package patient;


/**
* patient/PatientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Patient.idl
* Sunday, February 20, 2022 12:41:36 AM EST
*/

public interface PatientOperations 
{
  boolean bookAppointment (String patientId, appointment.AppointmentType type, String appointmentId);
  String getAppointmentSchedule (String patientId);
  boolean cancelAppointment (String patientId, appointment.AppointmentType type, String appointmentId);
  boolean swapAppointment (String patientId, appointment.AppointmentType oldType, String oldAppointmentId, appointment.AppointmentType newType, String newAppointmentId);
} // interface PatientOperations
