package patient;

/**
* patient/PatientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Patient.idl
* Sunday, February 20, 2022 12:41:36 AM EST
*/

public final class PatientHolder implements org.omg.CORBA.portable.Streamable
{
  public patient.Patient value = null;

  public PatientHolder ()
  {
  }

  public PatientHolder (patient.Patient initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = patient.PatientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    patient.PatientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return patient.PatientHelper.type ();
  }

}
