package HelloApp;


/**
* HelloApp/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Saturday, February 19, 2022 10:50:48 PM EST
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
