package cobar_entity.patient;


/**
* patient/Patient.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dams.idl
* Tuesday, March 8, 2022 3:01:23 PM EST
*/

public interface Patient extends PatientOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Patient
