package cobar_entity.patient;

/**
* patient/PatientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dams.idl
* Tuesday, March 8, 2022 3:01:23 PM EST
*/

public final class PatientHolder implements org.omg.CORBA.portable.Streamable
{
  public Patient value = null;

  public PatientHolder ()
  {
  }

  public PatientHolder (Patient initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PatientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PatientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PatientHelper.type ();
  }

}
