package appointment;

/**
* appointment/AppointmentAvailabilityHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Patient.idl
* Sunday, February 20, 2022 12:41:36 AM EST
*/

public final class AppointmentAvailabilityHolder implements org.omg.CORBA.portable.Streamable
{
  public appointment.AppointmentAvailability value = null;

  public AppointmentAvailabilityHolder ()
  {
  }

  public AppointmentAvailabilityHolder (appointment.AppointmentAvailability initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = appointment.AppointmentAvailabilityHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    appointment.AppointmentAvailabilityHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return appointment.AppointmentAvailabilityHelper.type ();
  }

}
