package appointment;


/**
* appointment/Appointment.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Patient.idl
* Sunday, February 20, 2022 12:41:36 AM EST
*/

public final class Appointment implements org.omg.CORBA.portable.IDLEntity
{
  public String id = null;
  public int capacity = (int)0;
  public String patientIds[] = null;
  public appointment.AppointmentType type = null;

  public Appointment ()
  {
  } // ctor

  public Appointment (String _id, int _capacity, String[] _patientIds, appointment.AppointmentType _type)
  {
    id = _id;
    capacity = _capacity;
    patientIds = _patientIds;
    type = _type;
  } // ctor

} // class Appointment
