package appointment;

/**
* appointment/AppointmentHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Patient.idl
* Sunday, February 20, 2022 12:41:36 AM EST
*/

public final class AppointmentHolder implements org.omg.CORBA.portable.Streamable
{
  public appointment.Appointment value = null;

  public AppointmentHolder ()
  {
  }

  public AppointmentHolder (appointment.Appointment initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = appointment.AppointmentHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    appointment.AppointmentHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return appointment.AppointmentHelper.type ();
  }

}
