package appointment;


/**
* appointment/AppointmentAvailability.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Patient.idl
* Sunday, February 20, 2022 12:41:36 AM EST
*/

public final class AppointmentAvailability implements org.omg.CORBA.portable.IDLEntity
{
  public String appointmentId = null;
  public int availability = (int)0;

  public AppointmentAvailability ()
  {
  } // ctor

  public AppointmentAvailability (String _appointmentId, int _availability)
  {
    appointmentId = _appointmentId;
    availability = _availability;
  } // ctor

} // class AppointmentAvailability
