package appointment;


/**
* appointment/AppointmentTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Patient.idl
* Sunday, February 20, 2022 12:41:36 AM EST
*/

abstract public class AppointmentTypeHelper
{
  private static String  _id = "IDL:appointment/AppointmentType:1.0";

  public static void insert (org.omg.CORBA.Any a, appointment.AppointmentType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static appointment.AppointmentType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (appointment.AppointmentTypeHelper.id (), "AppointmentType", new String[] { "Physician", "Surgeon", "Dental"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static appointment.AppointmentType read (org.omg.CORBA.portable.InputStream istream)
  {
    return appointment.AppointmentType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, appointment.AppointmentType value)
  {
    ostream.write_long (value.value ());
  }

}
