package appointment;

/**
* appointment/AppointmentTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Patient.idl
* Sunday, February 20, 2022 12:41:36 AM EST
*/

public final class AppointmentTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public appointment.AppointmentType value = null;

  public AppointmentTypeHolder ()
  {
  }

  public AppointmentTypeHolder (appointment.AppointmentType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = appointment.AppointmentTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    appointment.AppointmentTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return appointment.AppointmentTypeHelper.type ();
  }

}
