package appointment;


/**
* appointment/AppointmentType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Patient.idl
* Sunday, February 20, 2022 12:41:36 AM EST
*/

public class AppointmentType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static appointment.AppointmentType[] __array = new appointment.AppointmentType [__size];

  public static final int _Physician = 0;
  public static final appointment.AppointmentType Physician = new appointment.AppointmentType(_Physician);
  public static final int _Surgeon = 1;
  public static final appointment.AppointmentType Surgeon = new appointment.AppointmentType(_Surgeon);
  public static final int _Dental = 2;
  public static final appointment.AppointmentType Dental = new appointment.AppointmentType(_Dental);

  public int value ()
  {
    return __value;
  }

  public static appointment.AppointmentType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected AppointmentType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class AppointmentType
