package cobar_entity.appointment;

/**
* appointment/AppointmentTypeDtoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Patient.idl
* Sunday, February 20, 2022 4:56:02 PM EST
*/

public final class AppointmentTypeDtoHolder implements org.omg.CORBA.portable.Streamable
{
  public AppointmentTypeDto value = null;

  public AppointmentTypeDtoHolder ()
  {
  }

  public AppointmentTypeDtoHolder (AppointmentTypeDto initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AppointmentTypeDtoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AppointmentTypeDtoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AppointmentTypeDtoHelper.type ();
  }

}
