package cobar_entity.appointment;


/**
* appointment/AppointmentDtoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Patient.idl
* Sunday, February 20, 2022 4:56:02 PM EST
*/

abstract public class AppointmentDtoHelper
{
  private static String  _id = "IDL:appointment/AppointmentDto:1.0";

  public static void insert (org.omg.CORBA.Any a, AppointmentDto that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static AppointmentDto extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "capacity",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "patientIds",
            _tcOf_members0,
            null);
          _tcOf_members0 = AppointmentTypeDtoHelper.type ();
          _members0[3] = new org.omg.CORBA.StructMember (
            "type",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (AppointmentDtoHelper.id (), "AppointmentDto", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static AppointmentDto read (org.omg.CORBA.portable.InputStream istream)
  {
    AppointmentDto value = new AppointmentDto ();
    value.id = istream.read_string ();
    value.capacity = istream.read_long ();
    int _len0 = istream.read_long ();
    value.patientIds = new String[_len0];
    for (int _o1 = 0;_o1 < value.patientIds.length; ++_o1)
      value.patientIds[_o1] = istream.read_string ();
    value.type = AppointmentTypeDtoHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, AppointmentDto value)
  {
    ostream.write_string (value.id);
    ostream.write_long (value.capacity);
    ostream.write_long (value.patientIds.length);
    for (int _i0 = 0;_i0 < value.patientIds.length; ++_i0)
      ostream.write_string (value.patientIds[_i0]);
    AppointmentTypeDtoHelper.write (ostream, value.type);
  }

}
