package cobar_entity.appointment;

/**
 * appointment/AppointmentAvailabilityDtoHolder.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from dams.idl Sunday, February 20, 2022 6:15:22 PM EST
 */
public final class AppointmentAvailabilityDtoHolder implements org.omg.CORBA.portable.Streamable {
  public AppointmentAvailabilityDto value = null;

  public AppointmentAvailabilityDtoHolder() {}

  public AppointmentAvailabilityDtoHolder(AppointmentAvailabilityDto initialValue) {
    value = initialValue;
  }

  public void _read(org.omg.CORBA.portable.InputStream i) {
    value = AppointmentAvailabilityDtoHelper.read(i);
  }

  public void _write(org.omg.CORBA.portable.OutputStream o) {
    AppointmentAvailabilityDtoHelper.write(o, value);
  }

  public org.omg.CORBA.TypeCode _type() {
    return AppointmentAvailabilityDtoHelper.type();
  }
}
