package cobar_entity.appointment;


/**
* appointment/AppointmentTypeDto.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Patient.idl
* Sunday, February 20, 2022 4:56:02 PM EST
*/

public class AppointmentTypeDto implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static AppointmentTypeDto[] __array = new AppointmentTypeDto [__size];

  public static final int _Physician = 0;
  public static final AppointmentTypeDto Physician = new AppointmentTypeDto(_Physician);
  public static final int _Surgeon = 1;
  public static final AppointmentTypeDto Surgeon = new AppointmentTypeDto(_Surgeon);
  public static final int _Dental = 2;
  public static final AppointmentTypeDto Dental = new AppointmentTypeDto(_Dental);

  public int value ()
  {
    return __value;
  }

  public static AppointmentTypeDto from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected AppointmentTypeDto (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class AppointmentTypeDto
